services:
  php:
    image: tugboatqa/php:8.3-apache
    default: true
    http: false
    depends: mysql
    commands:
      init: |
        # Repeat the steps from https://github.com/TugboatQA/drupal/blob/main/Dockerfile
        # We have to do this b/c we're depending on the tugboatqa/php:8.3-apache
        # directly instead of tugboatqa/drupal:10.4 b/c that image is pinned to
        # PHP 8.1 and we need at least PHP 8.3.
        DRUPAL_COMPOSER_ROOT="/var/www/drupal"
        DRUPAL_DOCROOT="/var/www/drupal/web"
        COMPOSER_MEMORY_LIMIT=-1

        set -x && apt-get update
        apt-get -y install libzip-dev
        apt-get clean
        docker-php-ext-install zip
        docker-php-ext-install opcache
        a2enmod headers rewrite
        composer create-project drupal/recommended-project:10.4 $DRUPAL_COMPOSER_ROOT
        cd $DRUPAL_COMPOSER_ROOT
        composer require drush/drush --with-all-dependencies
        mkdir -p $DRUPAL_DOCROOT/sites/default/files
        chgrp www-data $DRUPAL_DOCROOT/sites/default/files
        chmod 2775 $DRUPAL_DOCROOT/sites/default/files
        ln -snf $DRUPAL_DOCROOT $DOCROOT

        # Install ImageMagick.
        apt-get update
        apt-get install -y imagemagick

      update: |
        set -eux
        cd $DRUPAL_COMPOSER_ROOT
        composer config minimum-stability dev

        # Increase memory
        echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/tugboat.ini

        # Install Drupal on the site.
        vendor/bin/drush \
          --yes \
          --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat \
          --site-name="Live preview for ${TUGBOAT_PREVIEW_NAME}" \
          --account-pass=admin \
          site:install standard
        echo "\$settings['trusted_host_patterns'] = ['\.tugboatqa\.com\$'];" >> $DOCROOT/sites/default/settings.php
        mkdir -p $DRUPAL_DOCROOT/sites/default/files
        chgrp -R www-data $DRUPAL_DOCROOT/sites/default/files
        chmod 2775 $DRUPAL_DOCROOT/sites/default/files
        chmod -R g+w $DRUPAL_DOCROOT/sites/default/files

        # Install drupal/core-recipe-unpack
        composer require drupal/core-recipe-unpack

        # Add our recipe as a composer path repository, so that it can be
        # added with composer require.
        composer config repositories.placeholder-glossary --json "{\"type\": \"path\", \"url\": \"$TUGBOAT_ROOT\"}"
        composer require lullabot/placeholder-glossary:*

        # Apply the recipe.
        cd $DRUPAL_COMPOSER_ROOT/web
        php core/scripts/drupal recipe $TUGBOAT_ROOT -v

      build: |
        set -eux
        cd $DRUPAL_COMPOSER_ROOT
        composer install --optimize-autoloader
        vendor/bin/drush --yes updb
        vendor/bin/drush cache:rebuild
  mysql:
    image: tugboatqa/mariadb
